name: C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: multiple jobs
      run: gcc --version
    - name: configure
      run: ./configure
    - name: make
      run: |
        make
        pwd
    - name: make test
      run: |
        make test
        pwd
    - name: tar hello
      run: |
        tar -zcvf hello.tar.gz ./hello
        pwd
        
        
    # 发布 Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hello.tar.gz
        asset_name: hello.tar.gz
        asset_content_type: application/x-tgz

