name: C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: multiple jobs
      run: |
        sudo echo 123456
        gcc --version
    - name: configure
      run: ./configure
    - name: make
      run: |
        make
        pwd
    - name: make test
      run: |
        make test
        pwd
    - name: tar hello
      run: tar -zcvf hello.tar.gz ./hello
    - name: Upload bundle
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        src: ./hello.tar.gz
        dest: /soft
