name: C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: multiple jobs
      run: gcc --version
    - name: configure
      run: ./configure
    - name: make
      run: |
        make
        pwd
    - name: make test
      run: |
        make test
        pwd
    - name: tar hello
      run: |
        tar -zcvf hello.tar.gz ./hello
        pwd
    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: hello.tar.gz
        path: /home/runner/work/github-actions-test/github-actions-test/hello.tar.gz
    
    #- name: download
    #  uses: zhenyuWang/Upload-File-Action@v1.0.1
    #  with:
    #    username: ${{ secrets.USERNAME101 }}
    #    server: ${{ secrets.HOST101 }}
    #    port: ${{ secrets.PORT101 }}
    #    ssh_private_key: ${{ secrets.PRIVATE_KEY101 }}
    #    local_path: /home/runner/work/github-actions-test/github-actions-test/hello.tar.gz
    #    target_path: /soft
    #    args: sftp
    
    - name: deploy
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: '/home/runner/work/github-actions-test/github-actions-test/hello.tar.gz'
        remote: '/soft'
        host: ${{ secrets.HOST101 }}
        port: ${{ secrets.PORT101 }}
        user: ${{ secrets.USER101 }}
        password: ${{ secrets.PASSWORD101 }}
        key: ${{ secrets.PRIVATE_KEY101 }}
