name: C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: multiple jobs
      run: gcc --version
    - name: configure
      run: ./configure
    - name: make
      run: |
        make
        pwd
    - name: make test
      run: |
        make test
        pwd
    - name: tar hello
      run: |
        sudo mkdir /soft
        tar -zcvf /soft/hello.tar.gz ./hello
    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: hello.tar.gz
        path: /soft/hello.tar.gz
