name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          sudo chmod 777 test.sh
          #sudo sh ./test.sh
          set +e
          rm 123456.txt
          
      - name: hello
        #if: ${{ failure() }}
        run: echo "hello"
      
      - uses: actions/upload-artifact@v3
        #if: ${{ failure() }}
        with:
          name: my-artifact
          path: ./test.txt

  second:
    #if: ${{ failure() }}
    needs: first
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
    
      - name: check test.txt
        run: |
          sudo ls ./test.txt
          echo "hello"
