name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          sudo touch test.txt
          sudo chmod 777 test.txt
          sudo echo 123 > test.txt
          sudo cat test.txt
          #sudo rm 123.txt
          
      - name: hello
        if: ${{ failure() }}
        run: echo "hello"
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test.txt

  second:
    needs: first
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
    
      - name: check test.txt
        run: sudo ls ./test.txt
