name: C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 7.3
        platform: x64
    - name: gcc version
      run: sudo gcc --version
